name: "run commit check for pr"
on:
  push:
    branches:
      - fakebranch
#
jobs:
  setup-version:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['3.1', '5.0']
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Clear toolcache
        shell: pwsh
        run: |
          $dotnetPaths = @("$env:ProgramFiles\dotnet", "$env:LocalAppData\Microsoft\dotnet")

          foreach ($srcPath in $dotnetPaths) {
            if (Test-Path $srcPath) {
              $dstPath = Join-Path ([IO.Path]::GetTempPath()) ([IO.Path]::GetRandomFileName())
              Move-Item -Path $srcPath -Destination $dstPath
              }
            }
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Check installed version
        shell: pwsh
        run: |
          $version = & dotnet --version
          Write-Host "Installed version: $version"
          if (-not $version.StartsWith("${{ matrix.dotnet-version }}")) { throw "Unexpected version" }